import type { NextPage } from "next";
import Head from "next/head";

import { Container, Heading } from "../styles/pages/Home";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Nubelson Fernandes | Developer &#38; Content Creator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Heading>
        <p>Hi, I am</p>
        <h1>Coming Soon...</h1>
      </Heading>
    </Container>
  );
};

export default Home;
